name: David Elmer
tagline: Senior Web developer with a passion for combining the art of design with the logic and structure of front-end programming.
location: Orlando, FL
linkedin: https://linkedin.com/in/davelmer/
github: https://github.com/phillycc
markdown: kramdown
pygments: false
