name: David Elmer
tagline: Software developer with a passion for front-end tech, AngularJS, and git.
location: Orlando, FL
linkedin: https://linkedin.com/in/davelmer/
github: https://github.com/phillycc
markdown: redcarpet
pygments: false
