name: David Elmer
tagline: Front-end developer with a passion for combining the art of design with the logic and sturcture of javascript programming.
location: Orlando, FL
linkedin: https://linkedin.com/in/davelmer/
github: https://github.com/phillycc
markdown: redcarpet
pygments: false
