name: David Elmer
tagline: Software developer with a passion for JavaScript, minimalist design, and git.
location: Orlando, FL
linkedin: http://linkedin.com/in/davelmer/
twitter: http://twitter.com/code_cheesecake
github: https://github.com/phillycc
markdown: redcarpet
pygments: false
